language: python

stages:
  - pre-tests
  - tests
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - stage: pre-tests
      install: pip install pre-commit==2.9.3
      script: pre-commit run --all-files --show-diff-on-failure --color always
      python: "3.9"
    - stage: pre-tests
      install: pip install flake8
      script: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      python: "3.9"

script: python setup.py test
