language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_script:
  - pip install flake8
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
script: python setup.py test
